project:
  type: website
  output-dir: ..\docs

about:
  template: broadside

website:
  title: "SSG VIP Overlay Study"
  search:
    location: navbar
    type: overlay
  navbar:
    background: primary
    search: true
    right: #changed nav menu items to align to the right
      - text: "Home"
        file: index.qmd
      - text: "Installation"
        file: installation.qmd
      - text: "Users Guide"
        file: usersguide.qmd
      - text: "About Team"
        file: about.qmd
    logo: assets/CS-icon-01.png #vcu computer science emblem 
    logo-href: /index.html

format:
  html:
    theme: assets/quarto_vcutheme.scss
    mainfont: 'Roboto' #vcu's body text font.
    toc: true
    html-math-method: katex

