project:
  type: website
  output-dir: ..\docs

#about:
#  template: broadside

website:
  title: "SSG VIP Internal Site"
  search:
    location: navbar
    type: overlay
  sidebar: false
  navbar:
    background: primary
    search: false
    right: #changed nav menu items to align to the right
      - text: "Home"
        file: index.qmd
    logo: assets/ssglogo.svg #vcu computer science emblem 
    logo-href: /index.html

format:
  html:
    theme: assets/quarto_ssgvip.scss
    mainfont: 'Roboto' #vcu's body text font.
    toc: true
    html-math-method: katex

